name: MBTI Personality profile
on:
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.16personalities.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_16personalities: yes
          plugin_16personalities_url: ${{ secrets.SIXTEEN_PERSONALITIES_URL }}
          plugin_16personalities_sections: personality, traits
          plugin_16personalities_scores: no
